### ISSUE TITLE
Functional-Light-JS/CONTRIBUTING.md

### ISSUE THREAD

**Issue by yanyixin** [ikcamp/Functional-Light-JS#2]
markdown file: [CONTRIBUTING.md](https://github.com/ikcamp/Functional-Light-JS/blob/master/CONTRIBUTING.md)
markdown file: [PULL_REQUEST_TEMPLATE.md](https://github.com/ikcamp/Functional-Light-JS/blob/master/PULL_REQUEST_TEMPLATE.md)
markdown file: [ISSUE_TEMPLATE.md](https://github.com/ikcamp/Functional-Light-JS/blob/master/ISSUE_TEMPLATE.md)

**Comment by BruceCham** [comment]
翻译认领 截止日期 2017-06-18

**Comment by yanyixin** [comment]
@brucecham  确认认领

**Comment by brucecham** [comment]
校对认领
