### ISSUE TITLE
Functional-Light-JS/foreword.md

### ISSUE THREAD

**Issue by yanyixin** [ikcamp/Functional-Light-JS#20]
markdown file: [foreword.md](https://github.com/ikcamp/Functional-Light-JS/blob/master/foreword.md)

**Comment by yanyixin** [comment]
翻译认领-2017-06-25

**Comment by yanyixin** [comment]
@yanyixin 确认认领

**Comment by cfanlife** [comment]
翻译认领-2017-06-11

**Comment by blueken** [comment]
翻译认领-2017-06-15 @yanyixin

**Comment by yanyixin** [comment]
@blueken  确认认领

**Comment by yanyixin** [comment]
@blueken  确认认领

**Comment by brucecham** [comment]
校对认领 截止日期 2017-07-09 @yanyixin
