### ISSUE TITLE
Functional-Light-JS/PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by yanyixin** [ikcamp/Functional-Light-JS#4]
markdown file: [PULL_REQUEST_TEMPLATE.md](https://github.com/ikcamp/Functional-Light-JS/blob/master/PULL_REQUEST_TEMPLATE.md)

**Comment by brucecham** [comment]
翻译认领 截止日期 2017-06-11

**Comment by sunshine940326** [comment]
翻译认领-2017-06-11
