### ISSUE TITLE
Functional-Light-JS/README.md

### ISSUE THREAD

**Issue by yanyixin** [ikcamp/Functional-Light-JS#5]
markdown file: [README.md](https://github.com/ikcamp/Functional-Light-JS/blob/master/README.md)

**Comment by brucecham** [comment]
翻译认领 截止日期 2017-06-11

**Comment by MatildaJin** [comment]
小组认领

**Comment by yanyixin** [comment]
@MatildaJin  确认认领

**Comment by brucecham** [comment]
校对认领 截止日期 2017-07-09 @yanyixin
