### ISSUE TITLE
这翻译的真心不走心, 有条件的建议读原文

### ISSUE THREAD

**Issue by mangitick** [ikcamp/Functional-Light-JS#60]

**Comment by blueken** [comment]
本文是很多伙伴一起翻译的，完成后进行交差评审，力求做到最好。
受制于大家英文水平有差异，技术理解程度有深浅，出现了翻译不理解的情况，向大家很示抱歉。

技术书籍，毫无疑问应该首先阅读原文。
英文水平高的伙伴们，发现文中有翻译不理解的地方，可以针对性的指出。或者直拉提一个PR,  让我们一起把翻译做地更好。
